environment:
  matrix:
    - MSVC_PLATFORM: x86
      PYTHON_ROOT: Python27
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    - MSVC_PLATFORM: x86
      PYTHON_ROOT: Python34
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - MSVC_PLATFORM: x86
      PYTHON_ROOT: Python35
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - MSVC_PLATFORM: x64
      PYTHON_ROOT: Python35-x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - MSVC_PLATFORM: x86
      PYTHON_ROOT: Python36
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - MSVC_PLATFORM: x64
      PYTHON_ROOT: Python36-x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

build_script:
  - .appveyor/msvc.bat

deploy: off
